class EasyDanmaku{constructor(e){this.container=this.checkParams(e),this.pathname=e.page||null,this.wrapperStyle=e.wrapperStyle||null,this.line=e.line||10,this.speed=e.speed||5,this.runtime=e.runtime||10,this.colourful=e.colourful||!1,this.loop=e.loop||!1,this.hover=e.hover||!1,this.coefficient=e.coefficient||1.38,this.originIndex=0,this.originList=null,this.offsetValue=this.container.offsetHeight/this.line,this.vipIndex=0,this.overflowArr=[],this.clearIng=!1,this.cleartimer=null,this.init(),this.handleEvents(e)}handleEvents(e){this.onComplete=e.onComplete||null,this.onHover=e.onHover||null}init(){this.runstatus=1,this.aisle=[],this.container.style.overflow="hidden",this.hover&&this.handleMouseHover(),"relative"!==Utils.getStyle(this.container,"position")&&"fixed"!==Utils.getStyle(this.container,"position")&&(this.container.style.position="relative");for(let e=0;e<this.line;e++)this.aisle.push({normalRow:!0,vipRow:!0})}checkParams(e){if(!document.querySelector(e.el))throw`Could not find the ${e.el} element`;if(e.wrapperStyle&&"string"!=typeof e.wrapperStyle)throw"The type accepted by the wrapperStyle parameter is string";if(e.line&&"number"!=typeof e.line)throw"The type accepted by the line parameter is number";if(e.speed&&"number"!=typeof e.speed)throw"The type accepted by the speed parameter is number";if(e.colourful&&"boolean"!=typeof e.colourful)throw"The type accepted by the colourful parameter is boolean";if(e.runtime&&"number"!=typeof e.runtime)throw"The type accepted by the runtime parameter is number";if(e.loop&&"boolean"!=typeof e.loop)throw"The type accepted by the loop parameter is boolean";if(e.coefficient&&"number"!=typeof e.coefficient)throw"The type accepted by the coefficient parameter is number";if(e.hover&&"boolean"!=typeof e.hover)throw"The type accepted by the hover parameter is boolean";if(e.onComplete&&"function"!=typeof e.onComplete)throw"The type accepted by the onComplete parameter is function";if(e.onHover&&"function"!=typeof e.onHover)throw"The type accepted by the onHover parameter is function";return document.querySelector(e.el)}send(e,o=null,l=null){if(0==this.runstatus)this.overflowArr.push({content:e,normalClass:o});else if(!(e.length<1)){let t=document.createElement("div"),i=0,r=this.speed,s=null,n=0;function a(){if(i=Math.round(Math.random()*(this.line-1)),this.aisle[i].normalRow){this.aisle[i].normalRow=!1,this.container.appendChild(t),r+=t.offsetWidth/t.parentNode.offsetWidth*2,t.style.cssText=`
                    text-align:center;
                    min-width:130px;
                    will-change: transform;
                    position:absolute;
                    right: -${t.offsetWidth+130}px;
                    transition: transform ${r}s linear;
                    transform: translateX(-${t.parentNode.offsetWidth+t.offsetWidth+130}px);
                    top: ${i*this.offsetValue}px;
                    line-height:${this.offsetValue}px;
                    color:${this.colourful?"#"+("00000"+(16777216*Math.random()<<0).toString(16)).substr(-6):void 0}
                `;let e=(t.parentNode.offsetWidth+t.offsetWidth)/r/60;s=setInterval(()=>{(n+=e)>t.offsetWidth*this.coefficient&&(this.aisle[i].normalRow=!0,clearInterval(s))},16.66),setTimeout(()=>{1!=t.getAttribute("relieveDel")&&(l&&l({runtime:r,target:t,width:t.offsetWidth}),t.remove())},1e3*r)}else this.aisle.some(e=>!0===e.normalRow)?a.call(this):(this.overflowArr.push({content:e,normalClass:o}),this.clearIng||this.clearOverflowDanmakuArray())}t.innerHTML=e,t.style.display="inline-block",t.classList.add("default-style"),(o||this.wrapperStyle)&&t.classList.add(o||this.wrapperStyle),a.call(this)}}batchSend(e,t=!1,i=null){var r=this.runtime||1.23*e.length;this.originList=e,this.hasAvatar=t,this.normalClass=i;let s=setInterval(()=>{location.pathname!=this.pathname&&clearInterval(s),this.originIndex>e.length-1?(clearInterval(s),this.originIndex=0,this.onComplete&&this.onComplete(),this.loop&&this.batchSend(this.originList,t,i)):(t?this.send(`${e[this.originIndex].url?'<a href="'+e[this.originIndex].url+'">':""}<img src=${e[this.originIndex].avatar}>
                        <p>${e[this.originIndex].content}</p>${e[this.originIndex].url?"</a>":""}
                    `,i||this.wrapperStyle):this.send(e[this.originIndex],i||this.wrapperStyle),this.originIndex++)},r/e.length*1e3)}centeredSend(e,t,i=3e3,r=null){let s=document.createElement("div"),n=0;function o(){this.aisle[n].vipRow?(this.container.appendChild(s),s.style.cssText=`
                    position:absolute;
                    left:50%;
                    transform:translateX(-50%);
                    top: ${n*this.offsetValue}px;
                `,this.aisle[n].vipRow=!1,setTimeout(()=>{r&&r({duration:i,target:s,width:s.offsetWidth}),s.remove(),this.aisle[n].vipRow=!0},i)):++n>this.line-1||o.call(this)}s.innerHTML=e,(t||this.wrapperStyle)&&s.classList.add(t||this.wrapperStyle),o.call(this)}play(){var t=this.container.children;for(let e=0;e<t.length;e++)this.controlDanmakurunStatus(t[e],1);this.runstatus=1,0!==this.overflowArr.length&&this.clearOverflowDanmakuArray()}pause(){var t=this.container.children;for(let e=0;e<t.length;e++)this.controlDanmakurunStatus(t[e],0);this.runstatus=0}controlDanmakurunStatus(e,t){const i=1,r=0;var s,n=/-(\S*),/;t===i?(clearTimeout(e.timer),s=Utils.getStyle(e,"transform").match(n)[1],e.style.transition=`transform ${this.speed}s linear`,e.style.transform=`translateX(-${e.parentNode.offsetWidth+parseInt(s)+e.offsetWidth+130}px)`,e.timer=setTimeout(()=>{e.remove()},1e3*this.speed)):t===r&&(clearTimeout(e.timer),s=Utils.getStyle(e,"transform").match(n)[1],e.style.transition="transform 0s linear",e.style.transform=`translateX(-${s}px)`,e.setAttribute("relieveDel",1))}handleMouseHover(){Utils.eventDelegation(this.container,"default-style","mouseover",e=>{e.style["z-index"]=1e3,this.controlDanmakurunStatus(e,0),this.onHover&&this.onHover(e)}),Utils.eventDelegation(this.container,"default-style","mouseout",e=>{(e.style.zIndex=1)==this.runstatus&&this.controlDanmakurunStatus(e,1)})}clearOverflowDanmakuArray(){clearInterval(this.cleartimer),this.clearIng=!0;let e=0;this.cleartimer=setInterval(()=>{0===this.overflowArr.length?20<++e&&(clearInterval(this.cleartimer),this.clearIng=!1):(this.send(this.overflowArr[0].content,this.overflowArr[0].normalClass||this.wrapperStyle),this.overflowArr.shift())},500)}}class Utils{static getStyle(e,t){return window.getComputedStyle(e,null)[t]}static eventDelegation(e,t,i,r){e.addEventListener(i,e=>{try{e.target.className.includes(t)?r(e.target):e.target.parentNode.className.includes(t)&&r(e.target.parentNode)}catch(e){}})}}